services:
  lr3_pg:
    image: postgres:16-alpine
    container_name: lr3_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: lr3
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: lr3
    ports:
      - "15432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  parser:
    image: tasks_parser:mock
    container_name: parser
    restart: unless-stopped
    ports:
      - "18000:18000"
    environment:
      DB_URL: postgresql://lr3:12345678@lr3_pg:5432/lr3
    depends_on:
      - lr3_pg
      - redis

  celery-worker:
    image: tasks_parser:mock
    container_name: parser_celery_worker
    restart: unless-stopped
    command: celery -A celery_app worker -l info
    environment:
      DB_URL: postgresql://lr3:12345678@lr3_pg:5432/lr3
    depends_on:
      - lr3_pg
      - redis

  api:
    image: hackathon-app:latest
    container_name: api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      PARSER_URL: http://parser:18000
      DATABASE_URL: postgresql://lr3:12345678@lr3_pg:15432/lr3
    depends_on:
      - parser
      - celery-worker